version: '3.3'

services:

  postgresdb:
    image: postgres:15.3-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgresuser
      POSTGRES_PASSWORD: postgrespassword
      POSTGRES_DB: brontofundus_quartz_demo
    ports:
      - "2345:5432"
    networks:
      - quartznet

  quartz01:
    image: quartz-cluster-demo
    restart: unless-stopped
    depends_on:
      - postgresdb
    environment:
      INST_NAME: "01-peter"
      INST_WAITMILLIS: 15000
      SPRING_PROFILES_ACTIVE: dockercompose
    ports:
      - "18080:8080"
    networks:
      - quartznet

  quartz02:
    image: quartz-cluster-demo
    restart: unless-stopped
    depends_on:
      - postgresdb
    environment:
      INST_NAME: "02-paul"
      INST_WAITMILLIS: 25000
      SPRING_PROFILES_ACTIVE: dockercompose
    ports:
      - "28080:8080"
    networks:
      - quartznet

  quartz03:
    image: quartz-cluster-demo
    restart: unless-stopped
    depends_on:
      - postgresdb
    environment:
      INST_NAME: "03-friedolin"
      INST_WAITMILLIS: 35000
      SPRING_PROFILES_ACTIVE: dockercompose
    ports:
      - "38080:8080"
    networks:
      - quartznet

networks:
  quartznet:
